"""Generate UnrealScript IDs from the AP world catalog"""
import argparse
from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]


def render(source):
    data = runpy.run_path(str(source))
    pickups = data["PICKUPS"]
    maps = data["MAPS"]
    objectives = [(maps.index(name), step, actor, label)
                  for name, entries in data["ASSAULT_OBJECTIVES"].items()
                  for step, (actor, label) in enumerate(entries, 1)]
    families = tuple(name for name, _ in data["WEAPONS"]) + data["PICKUP_FAMILIES"]
    lines = ["// Generated by tools/catalog.py. Do not edit.",
             "class APCatalog extends Object;", "", f"var string Maps[{len(maps)}];",
             f"var byte MapMode[{len(maps)}], MapObjectiveCount[{len(maps)}];",
             "var string WeaponClasses[9];",
             "var string WeaponNames[9];",
             "var string AmmoFillerNames[9];",
             "var int AmmoFillerAmounts[9];",
             "var string AmmoClasses[9];",
             f"var string PickupFamilyNames[{len(data['PICKUP_FAMILIES'])}];",
             f"var string PickupTypeNames[{len(data['PICKUP_TYPE_NAMES'])}];",
             "struct APPickup { var byte MapIndex, FamilyIndex, TypeIndex; var vector Position; var string ItemClass, Label; var float Radius, Height; };",
             f"var APPickup Pickups[{len(pickups)}];", "var int PickupCount;", "",
             "struct APObjective { var byte MapIndex, Step; var string ActorName, Label; };",
             f"var APObjective Objectives[{len(objectives)}];", "var int ObjectiveCount;", "",
             "static function int ObjectiveMap(int I) { return default.Objectives[I].MapIndex; }",
             "static function int ObjectiveStep(int I) { return default.Objectives[I].Step; }",
             "static function string ObjectiveActor(int I) { return default.Objectives[I].ActorName; }",
             "static function string ObjectiveLabel(int I) { return default.Objectives[I].Label; }",
             "static function int PickupMap(int I) { return default.Pickups[I].MapIndex; }",
             "static function vector PickupPosition(int I) { return default.Pickups[I].Position; }",
             "static function string PickupClass(int I) { return default.Pickups[I].ItemClass; }",
             "static function string PickupLabel(int I) { return default.Pickups[I].Label; }",
             "static function int PickupFamily(int I) { return default.Pickups[I].FamilyIndex; }",
             "static function int PickupType(int I) { return default.Pickups[I].TypeIndex; }",
             "", "defaultproperties", "{",
             f"    PickupCount={len(pickups)}", f"    ObjectiveCount={len(objectives)}"]
    lines += [f'    Maps({i})="{name}"' for i, name in enumerate(maps)]
    for i, name in enumerate(maps):
        mode = 0 if name.startswith("DM-") else 1 if name.startswith("CTF-") else 2 if name.startswith("DOM-") else 3
        count = 100 if mode == 0 else len(data["objective_labels"](name))
        lines.append(f"    MapMode({i})={mode}")
        lines.append(f"    MapObjectiveCount({i})={count}")
    for i, (map_index, step, actor, label) in enumerate(objectives):
        lines.append(f'    Objectives({i})=(MapIndex={map_index},Step={step},ActorName="{actor}",Label="{label}")')
    lines += [f'    WeaponClasses({i})="{path}"' for i, (_, path) in enumerate(data["WEAPONS"])]
    lines += [f'    WeaponNames({i})="{name}"' for i, (name, _) in enumerate(data["WEAPONS"])]
    lines += [f'    AmmoFillerNames({i})="{name}"' for i, (name, _, _) in enumerate(data["AMMO_FILLERS"])]
    lines += [f'    AmmoFillerAmounts({i})={amount}' for i, (_, amount, _) in enumerate(data["AMMO_FILLERS"])]
    lines += [f'    AmmoClasses({i})="{name}"' for i, (_, _, name) in enumerate(data["AMMO_FILLERS"])]
    lines += [f'    PickupFamilyNames({i})="{name}"' for i, name in enumerate(data["PICKUP_FAMILIES"])]
    lines += [f'    PickupTypeNames({i})="{name}"' for i, name in enumerate(data["PICKUP_TYPE_NAMES"])]
    for i, pickup in enumerate(pickups):
        x, y, z = pickup["position"]
        classname = pickup["class"].lower()
        family = families.index(data["PICKUP_CLASS_FAMILY"][classname])
        pickup_type = data["PICKUP_TYPE_CLASSES"].index(classname)
        lines.append(f'    Pickups({i})=(MapIndex={pickup["map"]},FamilyIndex={family},TypeIndex={pickup_type},Position=(X={x},Y={y},Z={z}),'
                     f'ItemClass="{pickup["class"]}",Label="{pickup["actor"]}",'
                     f'Radius={pickup["radius"]},Height={pickup["height"]})')
    return "\n".join(lines + ["}", ""])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path,
                        default=ROOT.parent / "Archipelago_ut99/worlds/ut99/catalog.py")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "UT99AP/Classes/APCatalog.uc"
    content = render(args.source)
    if args.check:
        assert target.read_text() == content, "Run tools/catalog.py to update the client catalog"
    else:
        target.write_text(content, encoding="ascii")
